/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "AIExport.h"

#include "ExternalAI/Interface/AISEvents.h"
// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "OptionValues.h"
#include "SkirmishAI.h"
#include "WrappOOAICallback.h"

#include "ControllerAI.h"

// hack needed for cross-compile with mingw
#pragma push_macro("_WIN32_WINNT")
#undef _WIN32_WINNT
#define _WIN32_WINNT 0x0A00 // Windows 10 or later
#include "httplib.h"
#pragma pop_macro("_WIN32_WINNT")

#include "nlohmann/json.hpp"

#include <chrono>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <map>
#include <sstream>
#include <string>
#include <thread>

namespace {

using json = nlohmann::json;

std::string NormalizeProbeAddress(const std::string& bindAddress) {
	if (bindAddress == "0.0.0.0" || bindAddress == "::" || bindAddress == "[::]") {
		return "127.0.0.1";
	}

	return bindAddress;
}

bool ProbeInstanceEndpoint(const std::string& bindAddress, int port) {
	httplib::Client client(NormalizeProbeAddress(bindAddress), port);
	client.set_connection_timeout(0, 200000);
	client.set_read_timeout(0, 200000);
	client.set_write_timeout(0, 200000);

	auto response = client.Get("/observation");
	return response && response->status == 200;
}

struct InstanceRegistration {
	std::string bindAddress;
	int masterPort = -1;
	int instancePort = -1;
	int teamId = -1;
};

class CMasterRegistryServer {
public:
	static CMasterRegistryServer& GetInstance() {
		static CMasterRegistryServer instance;
		return instance;
	}

	InstanceRegistration ReserveInstance(int skirmishAIId, int teamId, const std::string& bindAddress, int masterPort) {
		if (teamId < 0) {
			throw std::runtime_error("ControllerAI: invalid team ID during init.");
		}

		std::lock_guard<std::mutex> lock(mutex);
		if (activeEntries.count(skirmishAIId) > 0 || pendingEntries.count(skirmishAIId) > 0) {
			throw std::runtime_error("ControllerAI: skirmish AI already registered.");
		}

		ValidateConfigurationLocked(bindAddress, masterPort);
		EnsureUniqueTeamLocked(teamId);
		StartMasterServerLocked();

		RegistryEntry entry;
		entry.skirmishAIId = skirmishAIId;
		entry.teamId = teamId;
		entry.bindAddress = configuredBindAddress;
		entry.instancePort = AllocateInstancePortLocked();

		pendingEntries[skirmishAIId] = entry;

		InstanceRegistration registration;
		registration.bindAddress = entry.bindAddress;
		registration.masterPort = configuredMasterPort;
		registration.instancePort = entry.instancePort;
		registration.teamId = entry.teamId;
		return registration;
	}

	void CommitInstance(int skirmishAIId) {
		std::lock_guard<std::mutex> lock(mutex);
		const auto it = pendingEntries.find(skirmishAIId);
		if (it == pendingEntries.end()) {
			throw std::runtime_error("ControllerAI: missing pending registry entry during commit.");
		}

		activeEntries[skirmishAIId] = it->second;
		pendingEntries.erase(it);
	}

	void RollbackInstance(int skirmishAIId) {
		bool shouldStop = false;
		{
			std::lock_guard<std::mutex> lock(mutex);
			pendingEntries.erase(skirmishAIId);
			shouldStop = activeEntries.empty() && pendingEntries.empty();
		}

		if (shouldStop) {
			StopMasterServer();
		}
	}

	void ReleaseInstance(int skirmishAIId) {
		bool shouldStop = false;
		{
			std::lock_guard<std::mutex> lock(mutex);
			activeEntries.erase(skirmishAIId);
			pendingEntries.erase(skirmishAIId);
			shouldStop = activeEntries.empty() && pendingEntries.empty();
		}

		if (shouldStop) {
			StopMasterServer();
		}
	}

private:
	struct RegistryEntry {
		int skirmishAIId = -1;
		int teamId = -1;
		std::string bindAddress;
		int instancePort = -1;
	};

	CMasterRegistryServer() : configuredMasterPort(-1), masterServerRunning(false) {
		masterServer.Get("/list", [this](const httplib::Request&, httplib::Response& res) {
			std::vector<RegistryEntry> entries;
			{
				std::lock_guard<std::mutex> lock(mutex);
				for (const auto& pair : activeEntries) {
					entries.push_back(pair.second);
				}
			}

			res.set_content(BuildRegistryJson(entries).dump(), "application/json");
		});
	}

	void ValidateConfigurationLocked(const std::string& bindAddress, int masterPort) {
		if (masterPort < 1024 || masterPort > 65535) {
			throw std::runtime_error("ControllerAI: master port must be between 1024 and 65535.");
		}

		if (configuredMasterPort == -1) {
			configuredBindAddress = bindAddress;
			configuredMasterPort = masterPort;
			return;
		}

		if (configuredBindAddress != bindAddress || configuredMasterPort != masterPort) {
			throw std::runtime_error("ControllerAI: all instances in a match must use the same bind address and master port.");
		}
	}

	void EnsureUniqueTeamLocked(int teamId) const {
		for (const auto& entry : activeEntries) {
			if (entry.second.teamId == teamId) {
				throw std::runtime_error("ControllerAI: duplicate team ID in master registry.");
			}
		}

		for (const auto& entry : pendingEntries) {
			if (entry.second.teamId == teamId) {
				throw std::runtime_error("ControllerAI: duplicate pending team ID in master registry.");
			}
		}
	}

	int AllocateInstancePortLocked() const {
		if (configuredMasterPort >= 65535) {
			throw std::runtime_error("ControllerAI: no instance ports available above the configured master port.");
		}

		for (int candidate = configuredMasterPort + 1; candidate <= 65535; ++candidate) {
			bool inUse = false;
			for (const auto& entry : activeEntries) {
				if (entry.second.instancePort == candidate) {
					inUse = true;
					break;
				}
			}
			if (inUse) {
				continue;
			}
			for (const auto& entry : pendingEntries) {
				if (entry.second.instancePort == candidate) {
					inUse = true;
					break;
				}
			}
			if (!inUse) {
				return candidate;
			}
		}

		throw std::runtime_error("ControllerAI: exhausted available instance ports.");
	}

	void StartMasterServerLocked() {
		if (masterServerRunning) {
			return;
		}

		if (masterThread.joinable()) {
			masterThread.join();
		}

		const std::string bindAddress = configuredBindAddress;
		const int masterPort = configuredMasterPort;
		masterServerRunning = true;
		masterThread = std::thread([this, bindAddress, masterPort]() {
			masterServer.listen(bindAddress.c_str(), masterPort);

			std::lock_guard<std::mutex> lock(mutex);
			masterServerRunning = false;
		});
	}

	void StopMasterServer() {
		masterServer.stop();
		if (masterThread.joinable()) {
			masterThread.join();
		}

		std::lock_guard<std::mutex> lock(mutex);
		configuredBindAddress.clear();
		configuredMasterPort = -1;
		masterServerRunning = false;
	}

	json BuildRegistryJson(const std::vector<RegistryEntry>& registryEntries) const {
		json jsonEntries = json::object();
		for (const RegistryEntry& entry : registryEntries) {
			const bool reachable = ProbeInstanceEndpoint(entry.bindAddress, entry.instancePort);

			std::ostringstream httpUrl;
			httpUrl << "http://" << entry.bindAddress << ":" << entry.instancePort;

			std::ostringstream wsUrl;
			wsUrl << "ws://" << entry.bindAddress << ":" << entry.instancePort << "/ws";

			std::ostringstream endpoint;
			endpoint << entry.bindAddress << ":" << entry.instancePort;

			jsonEntries[std::to_string(entry.teamId)] = {
				{"address", entry.bindAddress},
				{"port", entry.instancePort},
				{"reachable", reachable},
				{"endpoint", endpoint.str()},
				{"httpUrl", httpUrl.str()},
				{"wsUrl", wsUrl.str()},
				{"skirmishAIId", entry.skirmishAIId}
			};
		}

		return jsonEntries;
	}

	mutable std::mutex mutex;
	std::map<int, RegistryEntry> activeEntries;
	std::map<int, RegistryEntry> pendingEntries;
	httplib::Server masterServer;
	std::thread masterThread;
	std::string configuredBindAddress;
	int configuredMasterPort;
	bool masterServerRunning;
};

} // namespace

static std::map<int, controllerai::CControllerAI*> myAIs;
static std::map<int, springai::OOAICallback*>  myAICallbacks;

const static int ERROR_SHIFT = 100;

EXPORT(int) init(int skirmishAIId, const struct SSkirmishAICallback* innerCallback) {

	int ret = ERROR_SHIFT + 1;

	try {
		auto clb = std::unique_ptr<springai::OOAICallback>(springai::WrappOOAICallback::GetInstance(innerCallback, skirmishAIId));
		auto skirmishAI = std::unique_ptr<springai::SkirmishAI>(clb ? clb->GetSkirmishAI() : nullptr);
		if (!skirmishAI) {
			throw std::runtime_error("ControllerAI: failed to acquire SkirmishAI wrapper during init.");
		}

		std::string bindAddress = "127.0.0.1";
		int masterPort = 3017;
		springai::OptionValues* options = skirmishAI->GetOptionValues();
		if (options != nullptr) {
			const char* ipOpt = options->GetValueByKey("ip");
			if (ipOpt != nullptr) {
				bindAddress = ipOpt;
			}

			const char* portOpt = options->GetValueByKey("port");
			if (portOpt != nullptr) {
				masterPort = std::stoi(portOpt);
			}
		}

		const int teamId = skirmishAI->GetTeamId();
		InstanceRegistration registration = CMasterRegistryServer::GetInstance().ReserveInstance(
			skirmishAIId,
			teamId,
			bindAddress,
			masterPort
		);

		try {
			auto ai = std::unique_ptr<controllerai::CControllerAI>(new controllerai::CControllerAI(
				clb.get(),
				registration.bindAddress,
				registration.instancePort,
				registration.masterPort
			));

			CMasterRegistryServer::GetInstance().CommitInstance(skirmishAIId);
			myAIs[skirmishAIId] = ai.release();
			myAICallbacks[skirmishAIId] = clb.release();
		} catch (...) {
			CMasterRegistryServer::GetInstance().RollbackInstance(skirmishAIId);
			throw;
		}

		ret = 0;
	} catch (int err) {
		ret = err;
	} catch (const std::exception& e) {
		ret = ERROR_SHIFT + 2;
		(void)e;
	} catch (const std::string& s) {
		ret = ERROR_SHIFT + 3;
		(void)s;
	} catch (const char* s) {
		ret = ERROR_SHIFT + 4;
		(void)s;
	} catch (...) {
		ret = ERROR_SHIFT + 5;
	}

	return ret; // (ret != 0) => error
}

EXPORT(int) release(int skirmishAIId) {

	int ret = ERROR_SHIFT + 1;

	try {
		auto callbackIt = myAICallbacks.find(skirmishAIId);
		auto aiIt = myAIs.find(skirmishAIId);
		if (callbackIt == myAICallbacks.end() || aiIt == myAIs.end()) {
			throw std::runtime_error("ControllerAI: release requested for unknown skirmish AI ID.");
		}

		springai::OOAICallback* clb = callbackIt->second;
		controllerai::CControllerAI* ai = aiIt->second;
		myAICallbacks.erase(callbackIt);
		myAIs.erase(aiIt);
		CMasterRegistryServer::GetInstance().ReleaseInstance(skirmishAIId);

		delete ai;
		delete clb;

		ret = 0;
	} catch (int err) {
		ret = err;
	} catch (const std::exception& e) {
		ret = ERROR_SHIFT + 2;
		(void)e;
	} catch (const std::string& s) {
		ret = ERROR_SHIFT + 3;
		(void)s;
	} catch (const char* s) {
		ret = ERROR_SHIFT + 4;
		(void)s;
	} catch (...) {
		ret = ERROR_SHIFT + 5;
	}

	return ret; // (ret != 0) => error
}

EXPORT(int) handleEvent(int skirmishAIId, int topic, const void* data) {

	int ret = ERROR_SHIFT + 1;

	try {
		auto aiIt = myAIs.find(skirmishAIId);
		if (aiIt == myAIs.end() || aiIt->second == nullptr) {
			throw std::runtime_error("ControllerAI: event requested for unknown skirmish AI ID.");
		}

		ret = aiIt->second->HandleEvent(topic, data);
	} catch (int err) {
		ret = err;
	} catch (const std::exception& e) {
		ret = ERROR_SHIFT + 2;
		(void)e;
	} catch (const std::string& s) {
		ret = ERROR_SHIFT + 3;
		(void)s;
	} catch (const char* s) {
		ret = ERROR_SHIFT + 4;
		(void)s;
	} catch (...) {
		ret = ERROR_SHIFT + 5;
	}

	return ret; // (ret != 0) => error
}
