/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#ifndef _CPPTESTAI_CPPTESTAI_H
#define _CPPTESTAI_CPPTESTAI_H

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"

namespace controllerai {

/**
 * This is the main C++ entry point of this AI.
 * 
 * @author	Robin Vobruba <hoijui.quaero@gmail.com>
 */
class CControllerAI {

private:
	springai::OOAICallback* callback;
	int skirmishAIId;

public:
	CControllerAI(springai::OOAICallback* callback);
	~CControllerAI();

	int HandleEvent(int topic, const void* data);
}; // class CControllerAI

} // namespace controllerai

#endif // _CPPTESTAI_CPPTESTAI_H

